### ISSUE TITLE
DLL不足で起動できない（Qt5Network.dll）

### ISSUE THREAD

**Issue by sempreff** [vivisuke/openViVi#3]
- 事象
vivi64.exe 起動時に以下のエラーダイアログが表示され、起動できません。
「Qt5Network.dll が見つからないため、コードの実行を続行できません。プログラムを再インストールすると、この問題が解決する可能性があります。」
- 期待値
起動できること。必要な DLLは同梱されていると助かります。
もしユーザ側で何らかの手順が必要であれば、そのガイドがあることが望ましいです。
- その他
0034 までは起動できます。
- 環境
Windows10-64bit / vivi64-win-0035

**Comment by vivisuke** [comment]
本件は ver 0.036 で対処できたと思います。

**Comment by sempreff** [comment]
0036 は起動できました！対処ありがとうございます。
