### ISSUE TITLE
ツールバーの表示状態が維持されない

### ISSUE THREAD

**Issue by sempreff** [vivisuke/openViVi#7]
- 事象
ツールバーを非表示にしても起動し直すとまた表示されます。
- 再現方法
  1) vivi64.exe を起動する。
  2) MainToolBar、SearchToolBar、OtherToolBar を非表示にする。
  3) 終了する。
  4) vivi64.exe を起動する。（ツールバーが再度表示される）
- 期待値
終了時の状態が維持されること。
- その他
Outline についても同様です。
- 環境
Windows10-64bit 1909 / vivi64-win-0034

**Comment by vivisuke** [comment]
本件（ツールバーについてのみ）は ver 0.042 で対処できたと思います。

**Comment by sempreff** [comment]
対処ありがとうございます！画面が上下に狭いので、助かります。
Ctrl-F からの ESC も、いい感じです！
Outline については Q / Shift-Q を期待しつつ、待ちます。
