### ISSUE TITLE
行末の l で次行に進んでしまう

### ISSUE THREAD

**Issue by sempreff** [vivisuke/openViVi#8]
- 事象
行末で l したときに次の行に進んでしまいます。
- 期待値
行末にとどまること。
- その他
行頭の h は行頭にとどまります。これは期待通りです。
- 環境
Windows10-64bit 1909 / vivi64-win-0034

**Comment by vivisuke** [comment]
本件は ver 0.043 で対処できたと思います。

**Comment by sempreff** [comment]
0043 で動作良好です！対処ありがとうございました。
