### ISSUE TITLE
最終行の yyp が行単位にならない

### ISSUE THREAD

**Issue by sempreff** [vivisuke/openViVi#9]
- 事象
最終行に改行コードがないとき、yyp すると行の中身が行末に足されてしまいます。
- 期待値
行としてペーストされること。
- 環境
Windows10-64bit 1909 / vivi64-win-0034

**Comment by vivisuke** [comment]
本件は ver 0.048 で対処できたと思います。

**Comment by sempreff** [comment]
0.048 で行単位になりました！ありがとうございます。
* リリースのページが 0.047 だったので、待ってました（苦笑）。
* 改行コードが少し違和感ありますが、もう少し整理してから改めてご報告します。
